data:
  train_data_dir: "/content/data2/train"
  val_data_dir: "/content/data2/test"  
  test_data_dir: "/content/data2/test" 

model:
  num_classes: 2

training:
  is_train: true
  device: 'cuda'
  image_size: [224, 224]
  batch_size: 32
  learning_rate: 1e-5
  epochs: 10
  save_dir: './results'
  
testing:
  is_test: true
  model_path: "./results/model_7.pth"
